version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./ssl:/etc/nginx/ssl
    restart: unless-stopped
    networks:
      - collider-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server/uploads:/app/uploads
    restart: unless-stopped
    networks:
      - collider-network

networks:
  collider-network:
    driver: bridge