# Generated by Django 5.2 on 2025-04-29 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('welcome', 'Welcome'), ('draw_upcoming', 'Upcoming Draw'), ('draw_results', 'Draw Results'), ('winning', 'Winning Notification'), ('deposit_success', 'Deposit Successful'), ('deposit_failed', 'Deposit Failed'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_processed', 'Withdrawal Processed'), ('withdrawal_failed', 'Withdrawal Failed'), ('ticket_purchased', 'Ticket Purchased'), ('promo', 'Promotional'), ('system', 'System Notification')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('is_sms_sent', models.BooleanField(default=False)),
                ('is_push_sent', models.BooleanField(default=False)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
