# Generated by Django 4.2.9 on 2025-04-28 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Draw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("draw_number", models.IntegerField()),
                ("draw_date", models.DateTimeField()),
                ("main_numbers", models.JSONField(blank=True, null=True)),
                ("extra_numbers", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "jackpot_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("ticket_count", models.IntegerField(default=0)),
                (
                    "verification_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LotteryGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("main_numbers_count", models.IntegerField()),
                ("main_numbers_range", models.IntegerField()),
                ("extra_numbers_count", models.IntegerField(default=0)),
                ("extra_numbers_range", models.IntegerField(default=0)),
                ("ticket_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("draw_days", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="lottery_images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrizeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("main_numbers_matched", models.IntegerField()),
                ("extra_numbers_matched", models.IntegerField()),
                ("odds", models.CharField(max_length=50)),
                (
                    "prize_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed Amount"),
                            ("percentage", "Percentage of Pool"),
                            ("jackpot", "Jackpot"),
                        ],
                        default="fixed",
                        max_length=20,
                    ),
                ),
                (
                    "percentage_of_pool",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "lottery_game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prize_categories",
                        to="lottery.lotterygame",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("main_numbers", models.JSONField()),
                ("extra_numbers", models.JSONField()),
                ("is_quick_pick", models.BooleanField(default=False)),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
                (
                    "result_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("checked", "Checked"),
                            ("winning", "Winning"),
                            ("non_winning", "Non-Winning"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("matched_main_numbers", models.IntegerField(default=0)),
                ("matched_extra_numbers", models.IntegerField(default=0)),
                (
                    "winning_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="lottery.draw",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WinningTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prize_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lottery.prizecategory",
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="winning_info",
                        to="lottery.ticket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedNumberCombination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("main_numbers", models.JSONField()),
                ("extra_numbers", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lottery_game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_combinations",
                        to="lottery.lotterygame",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_combinations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DrawResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("winners_count", models.IntegerField(default=0)),
                ("prize_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="lottery.draw",
                    ),
                ),
                (
                    "prize_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lottery.prizecategory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="draw",
            name="lottery_game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draws",
                to="lottery.lotterygame",
            ),
        ),
    ]
