# Generated by Django 4.2.9 on 2025-04-28 17:25

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lottery", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="draw",
            options={"verbose_name": "Draw", "verbose_name_plural": "Draws"},
        ),
        migrations.AlterModelOptions(
            name="drawresult",
            options={
                "verbose_name": "Draw Result",
                "verbose_name_plural": "Draw Results",
            },
        ),
        migrations.AlterModelOptions(
            name="lotterygame",
            options={
                "verbose_name": "Lottery Game",
                "verbose_name_plural": "Lottery Games",
            },
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"verbose_name": "Ticket", "verbose_name_plural": "Tickets"},
        ),
        migrations.AlterModelOptions(
            name="winningticket",
            options={
                "verbose_name": "Winning Ticket",
                "verbose_name_plural": "Winning Tickets",
            },
        ),
        migrations.AddField(
            model_name="draw",
            name="is_test",
            field=models.BooleanField(
                default=False, help_text="Indicates if this is a test draw"
            ),
        ),
        migrations.AddField(
            model_name="draw",
            name="public_verification_url",
            field=models.URLField(
                blank=True,
                help_text="URL for public verification of results",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="draw",
            name="rng_provider",
            field=models.CharField(
                default="crypto",
                help_text="Provider used for random number generation",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="draw",
            name="verification_data",
            field=models.JSONField(
                blank=True,
                help_text="Complete verification data for audit trail",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lotterygame",
            name="draw_time",
            field=models.TimeField(
                default="20:00:00", help_text="Time of the draw in UTC"
            ),
        ),
        migrations.AddField(
            model_name="lotterygame",
            name="prize_allocation_config",
            field=models.JSONField(
                blank=True, help_text="Configuration for prize allocation", null=True
            ),
        ),
        migrations.AddField(
            model_name="lotterygame",
            name="prize_allocation_type",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed Prize Amounts"),
                    ("percentage", "Percentage of Prize Pool"),
                    ("hybrid", "Hybrid (Mixed Fixed and Percentage)"),
                ],
                default="hybrid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lotterygame",
            name="rules",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional game rules and configurations",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP address used for purchase", null=True
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                help_text="ID of the purchase transaction",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="user_agent",
            field=models.TextField(
                blank=True, help_text="User agent used for purchase", null=True
            ),
        ),
        migrations.AddField(
            model_name="winningticket",
            name="payment_method",
            field=models.CharField(
                blank=True,
                help_text="Method used for prize payment",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="winningticket",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                help_text="Reference ID for the payment transaction",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="winningticket",
            name="verification_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="winningticket",
            name="verification_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="winningticket",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin user who verified the winning",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_winnings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="draw",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("verified", "Verified"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lotterygame",
            name="extra_numbers_count",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="lotterygame",
            name="extra_numbers_range",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(99),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="lotterygame",
            name="main_numbers_count",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="lotterygame",
            name="main_numbers_range",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="lotterygame",
            name="ticket_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="result_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("checked", "Checked"),
                    ("winning", "Winning"),
                    ("non_winning", "Non-Winning"),
                    ("paid", "Paid"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="winningticket",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("on_hold", "On Hold"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="draw",
            unique_together={("lottery_game", "draw_number")},
        ),
        migrations.AlterUniqueTogether(
            name="drawresult",
            unique_together={("draw", "prize_category")},
        ),
        migrations.AddIndex(
            model_name="draw",
            index=models.Index(fields=["status"], name="lottery_dra_status_c2fb40_idx"),
        ),
        migrations.AddIndex(
            model_name="draw",
            index=models.Index(
                fields=["draw_date"], name="lottery_dra_draw_da_9e8348_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="draw",
            index=models.Index(
                fields=["created_at"], name="lottery_dra_created_dd7a1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drawresult",
            index=models.Index(fields=["draw"], name="lottery_dra_draw_id_9f942e_idx"),
        ),
        migrations.AddIndex(
            model_name="drawresult",
            index=models.Index(
                fields=["created_at"], name="lottery_dra_created_3f4b10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lotterygame",
            index=models.Index(
                fields=["is_active"], name="lottery_lot_is_acti_322181_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lotterygame",
            index=models.Index(
                fields=["created_at"], name="lottery_lot_created_1c50f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["result_status"], name="lottery_tic_result__5d1bf4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["purchase_date"], name="lottery_tic_purchas_36af7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["user", "draw"], name="lottery_tic_user_id_2fe858_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="winningticket",
            index=models.Index(
                fields=["payment_status"], name="lottery_win_payment_67b91e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="winningticket",
            index=models.Index(
                fields=["created_at"], name="lottery_win_created_10cb76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="winningticket",
            index=models.Index(
                fields=["payment_date"], name="lottery_win_payment_efdba9_idx"
            ),
        ),
    ]
