# Generated by Django 4.2.9 on 2025-04-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lottery", "0002_add_verification_and_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="draw",
            name="winning_tickets_processed",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if winning tickets have been processed",
            ),
        ),
    ]
