# Generated by Django 4.2.9 on 2025-04-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lottery", "0003_draw_winning_tickets_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="winningticket",
            name="extra_numbers_matched",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="winningticket",
            name="main_numbers_matched",
            field=models.IntegerField(default=0),
        ),
    ]
