repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-json
    -   id: requirements-txt-fixer

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
        exclude: ^(backend/\*\/migrations/|frontend/)

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        exclude: ^(backend/\*\/migrations/|frontend/)

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        exclude: ^(backend/\*\/migrations/|frontend/)

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.44.0
    hooks:
    -   id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
        -   eslint@8.44.0
        -   eslint-plugin-react@7.32.2
        -   eslint-plugin-jsx-a11y@6.7.1
        -   eslint-plugin-react-hooks@4.6.0
        exclude: ^backend/