apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: euro-lottery-jaeger
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:latest
    options:
      log-level: info
  storage:
    type: memory
    options:
      memory:
        max-traces: 100000
  ingress:
    enabled: false
  ui:
    options:
      dependencies:
        menuEnabled: true
      tracking:
        gaID: ""
  agent:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "14271"
  query:
    options:
      query:
        base-path: /jaeger