# Generated by Django 5.2 on 2025-04-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='crypto_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='crypto_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='crypto_memo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='crypto_network',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_account', 'Bank Account'), ('e_wallet', 'E-Wallet'), ('crypto_wallet', 'Cryptocurrency Wallet')], max_length=20),
        ),
    ]
